ALTER TABLE moves ADD COLUMN IF NOT EXISTS scheduled_time TIMESTAMP NULL;
ALTER TABLE moves ADD COLUMN IF NOT EXISTS addressee VARCHAR(255) NULL;
ALTER TABLE moves ADD COLUMN IF NOT EXISTS recipient_phone_number VARCHAR(50) NULL;
